import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  console.log('Clearing database...');
  await prisma.infrastructureMetric.deleteMany();
  await prisma.infrastructureNode.deleteMany();
  await prisma.workforceUnit.deleteMany();
  await prisma.camera.deleteMany();
  await prisma.mobilitySnapshot.deleteMany();
  await prisma.crowdSnapshot.deleteMany();
  await prisma.incident.deleteMany();
  await prisma.match.deleteMany();
  await prisma.zone.deleteMany();
  await prisma.venue.deleteMany();
  await prisma.organization.deleteMany();

  console.log('Creating organization...');
  const org = await prisma.organization.create({
    data: {
      name: 'Global Arena Partners',
      createdById: 'system',
      country: 'US',
    },
  });

  console.log('Creating venue...');
  const venue = await prisma.venue.create({
    data: {
      organizationId: org.id,
      name: 'Metropolis Stadium',
      shortName: 'METRO',
      city: 'Metropolis City, NY',
      capacity: 85000,
      timezone: 'America/New_York',
    },
  });

  console.log('Creating zones...');
  const zonesToCreate = ['North Gate', 'South Gate', 'VIP Entrance', 'East Concourse', 'West Concourse'];
  const zones = [];
  for (const z of zonesToCreate) {
    const createdZone = await prisma.zone.create({
      data: {
        venueId: venue.id,
        name: z,
        shortCode: z.substring(0, 3).toUpperCase(),
        capacity: 5000,
        safeCapacity: 4500,
      }
    });
    zones.push(createdZone);
  }

  console.log('Creating match...');
  const match = await prisma.match.create({
    data: {
      organizationId: org.id,
      venueId: venue.id,
      matchNumber: 1,
      homeTeam: 'Lions',
      awayTeam: 'Tigers',
      scheduledAt: new Date(Date.now() + 86400000), // tomorrow
      kickoffAt: new Date(Date.now() + 86400000),
      endedAt: new Date(Date.now() + 86400000 + 10800000), // +3 hours
      matchStatus: 'scheduled',
      expectedAttendance: 82000,
    },
  });

  console.log('Creating crowd snapshots...');
  for (const zone of zones) {
    await prisma.crowdSnapshot.create({
      data: {
        matchId: match.id,
        venueId: venue.id,
        zoneId: zone.id,
        fanCount: Math.floor(Math.random() * 5000),
        safeCapacity: 5000,
        densityPct: Math.floor(Math.random() * 100),
        ingressRate: Math.floor(Math.random() * 200),
        recordedAt: new Date(),
      }
    });
  }

  console.log('Creating incidents...');
  const incidentTypes = ['medical', 'security', 'maintenance', 'crowd'];
  const zoneId = zones.length > 0 && zones[0] ? zones[0].id : 'default-zone';
  for (let i = 0; i < 5; i++) {
    await prisma.incident.create({
      data: {
        matchId: match.id,
        venueId: venue.id,
        title: `Incident ${i + 1}`,
        description: 'Autogenerated incident for testing',
        zoneId: zoneId,
        status: i % 2 === 0 ? 'open' : 'active',
        severityTier: i === 0 ? 1 : (i === 1 ? 2 : 3),
        reportedBy: 'system',
      }
    });
  }

  console.log('Creating workforce units...');
  const roles = ['security', 'medical', 'police', 'volunteer', 'transport'];
  for (let i = 0; i < 12; i++) {
    await prisma.workforceUnit.create({
      data: {
        organizationId: org.id,
        venueId: venue.id,
        name: `Unit Alpha-${i + 1}`,
        type: roles[Math.floor(Math.random() * roles.length)] || 'security',
        status: i % 4 === 0 ? 'busy' : 'available',
      }
    });
  }

  console.log('Creating infrastructure nodes...');
  const nodeTypes = ['turnstile', 'escalator', 'elevator', 'hvac', 'power', 'network'];
  for (let i = 0; i < 20; i++) {
    await prisma.infrastructureNode.create({
      data: {
        organizationId: org.id,
        venueId: venue.id,
        name: `${nodeTypes[Math.floor(Math.random() * nodeTypes.length)]}-${i + 1}`,
        type: nodeTypes[Math.floor(Math.random() * nodeTypes.length)] || 'network',
        status: Math.random() > 0.9 ? 'error' : (Math.random() > 0.7 ? 'warning' : 'healthy'),
      }
    });
  }

  console.log('Seeding complete! 🚀');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
